### ISSUE TITLE
Extra ; when sending selected text to MATLAB

### ISSUE THREAD

**Issue by bEiGeOnE78** [asparc/AutoMatlab#1]
If selected text in the .m file is `x = 1;` and I press `Ctrl + B`

then the command sent to the MATLAB command window is `x = 1;;` instead of the correct command `x = 1;`

**Comment by bEiGeOnE78** [comment]
The issue is in the `\Packages\AutoMatlab\Default (Windows).sublime-keymap`

```
 // Run current selection in Matlab
    {
        "keys": ["ctrl+b"], 
        "command": "run_matlab_command",
        "args": {"command": "$selection;"},
        "context": 
        [
            { "key": "selector", "operator": "equal", "operand": "source.matlab" },
            { "key": "selection_empty", "operator": "equal", "operand": false },
        ],
    },
```

Changing `"args": {"command": "$selection;"},` to `"args": {"command": "$selection"},` fixes the issue. I made the change in my user  keymap. Could this change also be made to the default keypmap?

**Comment by asparc** [comment]
Hi @bEiGeOnE78
Thanks for that suggestion I agree that removing the ';' makes more sense as the default. I'll change that in the near future!
If you have any other suggestions for additional features/changes, please let me know :-)
