### ISSUE TITLE
Add doc string support for class file?

### ISSUE THREAD

**Issue by oliverzzm** [asparc/AutoMatlab#2]
Hi! Thank you very much for developing this plugins. But I'd like to organize my matlab code into matlab class rather than separate function files. Current version does not support for autocompletion of class names in current folder, nor does it support doc string generation for matlab class. Would you spare some time to add this feature?

**Comment by asparc** [comment]
Hi @oliverzzm,
Sorry for never replying to your message. I'm not intending to add this functionality in the near future, as you probably noticed by now. As Matlab is not widely praised for it's approach to OOP, I'm a bit afraid that the Matlab classes are even more an unorganized zoo then the Matlab functions already were. Personally, I stay away from Matlab classes and it would take me too much time to make a decent extension to AutoMatlab for class support. My apologies.
